### ISSUE TITLE
Serverless 1.0.0-rc.2 Errors

### ISSUE THREAD

**Issue by seanfisher** [rajington/serverless-alexa-plugin#1]
I ran into a couple of issues with serverless version 1.0.0-rc.2.
- Having no custom resources in `serverless.yml` led to an error on [this line](https://github.com/rajington/serverless-alexa-plugin/blob/master/src/serverless-alexa-plugin.js#L14) where this.serverless.service.resources was undefined
- [This line](https://github.com/rajington/serverless-alexa-plugin/blob/master/src/serverless-alexa-plugin.js#L29) threw an error because `functionName` should be replaced by whatever the Cloudformation resource name of the lambda function is (not sure how to get that though)

Eventually I ran the plugin, let it error, then copied the resulting Cloudformation resource from .serverless into my serverless.yml as a custom Resource like so:

``` yml
# [...]
functions:
  alexaHandler:
    handler: handler.alexaHandler
# [...]

resources:
  Resources:
    AlexaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          "Fn::GetAtt":
            - AlexaHandlerLambdaFunction # Corresponds to function name above
            - Arn
        Action: lambda:InvokeFunction
        Principal: alexa-appkit.amazon.com
```

which seemed to work.
