### ISSUE TITLE
Getting error when attempting to deploy.

### ISSUE THREAD

**Issue by vangorra** [rajington/serverless-alexa-plugin#2]
```yaml
service: myService

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-west-2

package:
  individually: true
  exclude:
    - "**"

functions:
  graphql:
    handler: dist/app/AlexaHandler.handler
    timeout: 5
    package:
      include:
        - dist/app/AlexaHandler.js
    events:
      - alexaSkillsKit

plugins:
  - serverless-offline
  - serverless-alexa-plugin
```

```
TypeError: Cannot read property 'Resources' of undefined
    at ServerlessAlexaPlugin.compileAlexaEvents (<path>/node_modules/serverless-alexa-plugin/dist/serverless-alexa-plugin.js:84:46)
    at <path>/node_modules/serverless/lib/classes/PluginManager.js:160:50
    at tryCatcher (<path>/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (<path>/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:157:18)
    at Object.gotAccum (<path>/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (<path>/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (<path>/node_modules/serverless/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (<path>/node_modules/serverless/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (<path>/node_modules/serverless/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (<path>/node_modules/serverless/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (<path>/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (<path>/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (<path>/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
